name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  bios:
    runs-on: windows-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout microsoft/vscode
        uses: actions/checkout@v6
        
      - name: Download ExtremeROM tool
        shell: pwsh
        run: |
          Invoke-WebRequest `
            -Uri "https://github.com/extremerom/ExtremeROM/releases/download/V1/sp154137.exe" `
            -OutFile "sp154137.exe"
 
      - name: Extract BIOS
        shell: pwsh
        run: |
         New-Item -ItemType Directory -Path bios -Force

          .\sp154137.exe /help
          .\sp154137.exe /extract bios

      - name: Upload BIOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bios-extracted
          path: bios/
